import Footer from "@/components/Footer";
import "./globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "HobbyCare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
      </head>
      <body className="">
        <main className="h-fit max-w-[100vw] overflow-hidden">
          <Nav />
          <section className="relative overflow-hidden">{children}</section>
          <Footer />
        </main>
      </body>
    </html>
  );
}
